inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/cucumber'
    - 'bin/rspec'
    - 'bin/rake'

# Ignore gemfiles created by Appraisal
Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'

# Put development dependencies in the gemspec so rubygems.org knows about them.
# Don't complicate things in fixture apps and gems
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
  Exclude:
    - 'fixtures/**/*'

# TODO: Enable once the effects on using cukebot are clear and have been taken care of
Gemspec/RequireMFA:
  Enabled: false

# Spaces in strings with line continuations go at the beginning of the line.
Layout/LineContinuationLeadingSpace:
  EnforcedStyle: leading

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Assume the programmer knows precendence rules
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

# Spec blocks can be any size
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'

# This cop does not work properly with predicates that take arguments.
# TODO: Re-enable once https://github.com/rubocop/rubocop-rspec/issues/466 is resolved.
RSpec/PredicateMatcher:
  Enabled: false

# This cop doesn't seem to add much for us.
Style/FetchEnvVar:
  Enabled: false

# Be relatively lenient with line length
Layout/LineLength:
  Max: 94

inherit_from: .rubocop_todo.yml
