require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.4

# Spec blocks can be any size
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

# Be relatively lenient with line length
Layout/LineLength:
  Max: 94

inherit_from: .rubocop_todo.yml
