inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: disable
  # Keep this inline with the lowest ruby version in the gemspec
  TargetRubyVersion: 3.0
  # Display cop name / style guide references
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*

# A short line length prevents putting longer conditionals on one line.
Layout/LineLength:
  Max: 94

# This cop does not work properly with predicates that take arguments.
# TODO: Re-enable once https://github.com/rubocop/rubocop-rspec/issues/466 is resolved.
RSpec/PredicateMatcher:
  Enabled: false
