AllCops:
  Exclude:
    - tmp/**/*
  DisplayCopNames: true
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
Style/HashSyntax:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - lib/aruba/api.rb
    - lib/aruba/api/*.rb
    - lib/aruba/platform.rb

Metrics/AbcSize:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Cop supports --auto-correct.
Lint/RescueException:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 169
  Exclude:
    - lib/aruba/api.rb
    - lib/aruba/api/deprecated.rb
    - aruba.gemspec

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 18

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

Style/CaseEquality:
  Enabled: false

# Cop supports --auto-correct.
Style/CharacterLiteral:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: PreferredMethods.
Style/CollectionMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Configuration parameters: SupportedStyles.
Style/RaiseArgs:
  # EnforcedStyle: compact
  Enabled: false

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceBeforeFirstArg:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceAroundKeyword:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceAfterNot:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false
