# frozen_string_literal: true

# HACK: This uses odd syntax to make appraisal customization work on newer Rubies.
# See https://github.com/thoughtbot/appraisal/pull/214. Once that one has been
# released, we should use customize_gemfiles instead.
Customize.new heading: <<~HEADING.chomp
  frozen_string_literal: true

  This file was generated by Appraisal
HEADING

appraise 'cucumber_8' do
  gem 'cucumber', '~> 8.0'
end

appraise 'cucumber_9' do
  gem 'cucumber', ['~> 9.0', '>= 9.0.1']
end

appraise 'cucumber_10' do
  gem 'cucumber', '~> 10.0'
end

appraise 'rspec_4' do
  %w[rspec rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
    if lib == 'rspec'
      gem lib, git: 'https://github.com/rspec/rspec', branch: '4-0-dev'
    else
      gem lib, git: 'https://github.com/rspec/rspec', branch: '4-0-dev',
               glob: "#{lib}/#{lib}.gemspec"
    end
  end
end
