# frozen_string_literal: true

# HACK: This uses odd syntax to make appraisal customization work on newer Rubies.
# See https://github.com/thoughtbot/appraisal/pull/214. Once that one has been
# released, we should use customize_gemfiles instead.
Customize.new heading: <<~HEADING.chomp
  frozen_string_literal: true

  This file was generated by Appraisal
HEADING

appraise "cucumber_8" do
  gem "cucumber", "~> 8.0"
end

appraise "cucumber_9" do
  gem "cucumber", ["~> 9.0", ">= 9.0.1"]
end
