# Instructions
# ------------
#
# Build the Docker image using:
#
#   podman build -t test-aruba-podman -f Dockerfile.podman .
#
# You can pick any image name instead of test-aruba-podman, of course. After
# the build is done, run bash interactively inside the image like so:
#
#   podman run -v $PWD:/aruba --rm -it test-aruba-podman:latest bash
#
# The `-v $PWD:/aruba` will make the container pick up any changes to the
# code, so you can edit and re-run the tests.

FROM docker.io/ruby:4.0

RUN mkdir /aruba

# Run the rest of the steps in the aruba environment
WORKDIR /aruba

# Ensure Bundler 4.x is installed
RUN gem update bundler

# Add just the files needed for running bundle install
ADD Gemfile aruba.gemspec Manifest.txt /aruba/
ADD lib/aruba/version.rb /aruba/lib/aruba/version.rb
ADD exe/aruba /aruba/exe/aruba

# Install dependencies
RUN bundle

# Add the full source code
ADD . /aruba
